import 'package:flutter/material.dart';
import 'dart:math';

void main() {
  runApp(const WordGuessGame());
}

class WordGuessGame extends StatelessWidget {
  const WordGuessGame({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.teal,
        textTheme: const TextTheme(
          bodyLarge: TextStyle(fontSize: 18, fontFamily: 'RobotoMono'),
          bodyMedium: TextStyle(fontSize: 16, fontFamily: 'RobotoMono'),
        ),
      ),
      home: const SplashScreen(),
    );
  }
}

class SplashScreen extends StatelessWidget {
  const SplashScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [Colors.teal.shade400, Colors.teal.shade800],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              "Word Guess Game",
              style: TextStyle(
                fontSize: 40,
                fontWeight: FontWeight.bold,
                color: Colors.white,
                fontFamily: 'RobotoMono',
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 40),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.white,
                foregroundColor: Colors.teal,
                textStyle: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 15),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(30),
                ),
              ),
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const ModeSelectionScreen(),
                  ),
                );
              },
              child: const Text("Play"),
            ),
          ],
        ),
      ),
    );
  }
}

class ModeSelectionScreen extends StatelessWidget {
  const ModeSelectionScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Select Mode"),
        centerTitle: true,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                minimumSize: const Size(200, 50),
                textStyle: const TextStyle(fontSize: 18),
              ),
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) =>
                        const WordGameScreen(mode: "Easy", wordLength: 4),
                  ),
                );
              },
              child: const Text("Easy (4 letters)"),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                minimumSize: const Size(200, 50),
                textStyle: const TextStyle(fontSize: 18),
              ),
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) =>
                        const WordGameScreen(mode: "Medium", wordLength: 5),
                  ),
                );
              },
              child: const Text("Medium (5 letters)"),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                minimumSize: const Size(200, 50),
                textStyle: const TextStyle(fontSize: 18),
              ),
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) =>
                        const WordGameScreen(mode: "Hard", wordLength: 6),
                  ),
                );
              },
              child: const Text("Hard (6 letters)"),
            ),
          ],
        ),
      ),
    );
  }
}

class WordGameScreen extends StatefulWidget {
  final String mode;
  final int wordLength;

  const WordGameScreen({super.key, required this.mode, required this.wordLength});

  @override
  _WordGameScreenState createState() => _WordGameScreenState();
}

class _WordGameScreenState extends State<WordGameScreen> {
  final Map<String, List<String>> wordLists = {
    "Easy": [
      "area",
      "army",
      "baby",
      "back",
      "ball",
      "band",
      "bank",
      "base",
      "bill",
      "body",
      "book",
      "call",
      "card",
      "care",
      "case",
      "cash",
      "city",
      "club",
      "cost",
      "date",
      "deal",
      "door",
      "duty",
      "east",
      "edge",
      "face",
      "fact",
      "farm",
      "fear",
      "file",
      "film",
      "fire",
      "firm",
      "fish",
      "food",
      "foot",
      "form",
      "fund",
      "game",
      "girl",
      "goal",
      "gold",
      "hair",
      "half",
      "hall",
      "hand",
      "head",
      "help",
      "hill",
      "home",
      "hope",
      "hour",
      "idea",
      "jack",
      "john",
      "kind",
      "king",
      "lack",
      "lady",
      "land",
      "life",
      "line",
      "list",
      "look",
      "lord",
      "loss",
      "love",
      "mark",
      "mary",
      "mind",
      "miss",
      "move",
      "name",
      "need",
      "news",
      "note",
      "page",
      "pain",
      "pair",
      "park",
      "part",
      "past",
      "path",
      "paul",
      "plan",
      "play",
      "post",
      "race",
      "rain",
      "rate",
      "rest",
      "rise",
      "risk",
      "road",
      "rock",
      "role",
      "room",
      "rule",
      "sale",
      "seat",
      "shop",
      "show",
      "side",
      "sign",
      "site",
      "size",
      "skin",
      "sort",
      "star",
      "step",
      "task",
      "team",
      "term",
      "test",
      "text",
      "time",
      "tour",
      "town",
      "tree",
      "turn",
      "type",
      "unit",
      "user",
      "view",
      "wall",
      "week",
      "west",
      "wife",
      "will",
      "wind",
      "wine",
      "wood",
      "word",
      "work",
      "year",
      "bear",
      "beat",
      "blow",
      "burn",
      "cast",
      "come",
      "cook",
      "cope",
      "dare",
      "deal",
      "deny",
      "draw",
      "drop",
      "earn",
      "fail",
      "fall",
      "feel",
      "fill",
      "find",
      "gain",
      "give",
      "grow",
      "hang",
      "hate",
      "have",
      "head",
      "hear",
      "help",
      "hide",
      "hold",
      "hurt",
      "join",
      "jump",
      "keep",
      "kill",
      "know",
      "last",
      "lead",
      "lend",
      "lift",
      "like",
      "link",
      "live",
      "lose",
      "make",
      "mark",
      "meet",
      "must",
      "open",
      "pass",
      "pick",
      "pray",
      "pull",
      "push",
      "read",
      "rely",
      "ride",
      "ring",
      "roll",
      "save",
      "seek",
      "seem",
      "sell",
      "send",
      "shed",
      "shut",
      "sing",
      "slip",
      "stay",
      "step",
      "stop",
      "suit",
      "take",
      "talk",
      "tell",
      "tend",
      "vary",
      "vote",
      "wait",
      "wake",
      "walk",
      "want",
      "warn",
      "wash",
      "wear",
      "wish",
      "both",
      "else",
      "ergo",
      "lest",
      "once",
      "only",
      "plus",
      "sith",
      "than",
      "that",
      "then",
      "thou",
      "till",
      "unto",
      "when",
      "ably",
      "afar",
      "anew",
      "away",
      "damn",
      "dead",
      "deep",
      "down",
      "duly",
      "easy",
      "even",
      "ever",
      "fair",
      "fast",
      "flat",
      "full",
      "good",
      "hard",
      "here",
      "high",
      "idly",
      "just",
      "late",
      "long",
      "loud",
      "much",
      "near",
      "nice",
      "okay",
      "over",
      "part",
      "real",
      "slow",
      "solo",
      "soon",
      "sure",
      "this",
      "thus",
      "wide",
      "amid",
      "anti",
      "atop",
      "bout",
      "dahn",
      "doon",
      "from",
      "into",
      "nigh",
      "offa",
      "onto",
      "outa",
      "thro",
      "thru",
      "vice",
      "able",
      "bare",
      "bass",
      "blue",
      "bold",
      "busy",
      "calm",
      "cold",
      "cool",
      "damp",
      "dark",
      "deaf",
      "dear",
      "dual",
      "dull",
      "dumb",
      "evil",
      "fine",
      "fond",
      "foul",
      "free",
      "glad",
      "grey",
      "grim",
      "holy",
      "huge",
      "keen",
      "last",
      "lazy",
      "lone",
      "main",
      "male",
      "mass",
      "mean",
      "mere",
      "mild",
      "nazi",
      "neat",
      "next",
      "open",
      "oral",
      "pale",
      "pink",
      "poor",
      "pure",
      "rare",
      "real",
      "rear",
      "rich",
      "rude",
      "safe",
      "same",
      "sick",
      "slim",
      "soft",
      "sole",
      "sore",
      "tall",
      "thin",
      "tidy",
      "tiny",
      "tory",
      "true",
      "ugly",
      "vain",
      "vast",
      "warm",
      "wary",
      "weak",
      "wild",
      "wise",
      "zero"
    ],
    "Medium": [
      "about",
      "alert",
      "argue",
      "beach",
      "above",
      "alike",
      "arise",
      "began",
      "abuse",
      "alive",
      "array",
      "begin",
      "actor",
      "allow",
      "aside",
      "begun",
      "acute",
      "alone",
      "asset",
      "being",
      "admit",
      "along",
      "audio",
      "below",
      "adopt",
      "alter",
      "audit",
      "bench",
      "adult",
      "among",
      "avoid",
      "billy",
      "after",
      "anger",
      "award",
      "birth",
      "again",
      "angle",
      "aware",
      "black",
      "agent",
      "angry",
      "badly",
      "blame",
      "agree",
      "apart",
      "baker",
      "blind",
      "ahead",
      "apple",
      "bases",
      "block",
      "alarm",
      "apply",
      "basic",
      "blood",
      "album",
      "arena",
      "basis",
      "board",
      "boost",
      "buyer",
      "china",
      "cover",
      "booth",
      "cable",
      "chose",
      "craft",
      "bound",
      "calif",
      "civil",
      "crash",
      "brain",
      "carry",
      "claim",
      "cream",
      "brand",
      "catch",
      "class",
      "crime",
      "bread",
      "cause",
      "clean",
      "cross",
      "break",
      "chain",
      "clear",
      "crowd",
      "breed",
      "chair",
      "click",
      "crown",
      "brief",
      "chart",
      "clock",
      "curve",
      "bring",
      "chase",
      "close",
      "cycle",
      "broad",
      "cheap",
      "coach",
      "daily",
      "broke",
      "check",
      "coast",
      "dance",
      "brown",
      "chest",
      "could",
      "dated",
      "build",
      "chief",
      "count",
      "dealt",
      "built",
      "child",
      "court",
      "death",
      "debut",
      "entry",
      "forth",
      "group",
      "delay",
      "equal",
      "forty",
      "grown",
      "depth",
      "error",
      "forum",
      "guard",
      "doing",
      "event",
      "found",
      "guess",
      "doubt",
      "every",
      "frame",
      "guest",
      "dozen",
      "exact",
      "frank",
      "guide",
      "draft",
      "exist",
      "fraud",
      "happy",
      "drama",
      "extra",
      "fresh",
      "harry",
      "drawn",
      "faith",
      "front",
      "heart",
      "dream",
      "false",
      "fruit",
      "heavy",
      "dress",
      "fault",
      "fully",
      "hence",
      "drill",
      "fibre",
      "funny",
      "night",
      "drink",
      "field",
      "giant",
      "horse",
      "drive",
      "fifth",
      "given",
      "hotel",
      "drove",
      "fifty",
      "glass",
      "house",
      "dying",
      "fight",
      "globe",
      "human",
      "eager",
      "final",
      "going",
      "ideal",
      "early",
      "first",
      "grace",
      "image",
      "earth",
      "fixed",
      "grade",
      "index",
      "eight",
      "flash",
      "grand",
      "inner",
      "elite",
      "fleet",
      "grant",
      "input",
      "empty",
      "floor",
      "grass",
      "issue",
      "enemy",
      "fluid",
      "great",
      "irony",
      "enjoy",
      "focus",
      "green",
      "juice",
      "enter",
      "force",
      "gross",
      "joint",
      "judge",
      "metal",
      "media",
      "newly",
      "known",
      "local",
      "might",
      "noise",
      "label",
      "logic",
      "minor",
      "north",
      "large",
      "loose",
      "minus",
      "noted",
      "laser",
      "lower",
      "mixed",
      "novel",
      "later",
      "lucky",
      "model",
      "nurse",
      "laugh",
      "lunch",
      "money",
      "occur",
      "layer",
      "lying",
      "month",
      "ocean",
      "learn",
      "magic",
      "moral",
      "offer",
      "lease",
      "major",
      "motor",
      "often",
      "least",
      "maker",
      "mount",
      "order",
      "leave",
      "march",
      "mouse",
      "other",
      "legal",
      "music",
      "mouth",
      "ought",
      "level",
      "match",
      "movie",
      "paint",
      "light",
      "mayor",
      "needs",
      "paper",
      "power",
      "radio",
      "round",
      "panel",
      "press",
      "raise",
      "route",
      "phase",
      "price",
      "range",
      "royal",
      "phone",
      "pride",
      "rapid",
      "rural",
      "photo",
      "prime",
      "ratio",
      "scale",
      "piece",
      "print",
      "reach",
      "scene",
      "pilot",
      "prior",
      "ready",
      "scope",
      "pitch",
      "prize",
      "refer",
      "score",
      "place",
      "proof",
      "right",
      "sense",
      "plain",
      "proud",
      "rival",
      "serve",
      "plane",
      "prove",
      "river",
      "seven",
      "plant",
      "queen",
      "quick",
      "shall",
      "plate",
      "sixth",
      "stand",
      "shape",
      "point",
      "quiet",
      "roman",
      "share",
      "pound",
      "quite",
      "rough",
      "sharp",
      "sheet",
      "spare",
      "style",
      "times",
      "shelf",
      "speak",
      "sugar",
      "tired",
      "shell",
      "speed",
      "suite",
      "title",
      "shift",
      "spend",
      "super",
      "today",
      "shirt",
      "spent",
      "sweet",
      "topic",
      "shock",
      "split",
      "table",
      "total",
      "shoot",
      "spoke",
      "taken",
      "touch",
      "short",
      "sport",
      "taste",
      "tough",
      "shown",
      "staff",
      "taxes",
      "tower",
      "sight",
      "stage",
      "teach",
      "track",
      "since",
      "stake",
      "teeth",
      "trade",
      "sixty",
      "start",
      "texas",
      "treat",
      "sized",
      "state",
      "thank",
      "trend",
      "skill",
      "steam",
      "theft",
      "trial",
      "sleep",
      "steel",
      "their",
      "tried",
      "slide",
      "stick",
      "theme",
      "tries",
      "small",
      "still",
      "there",
      "truck",
      "smart",
      "stock",
      "these",
      "truly",
      "smile",
      "stone",
      "thick",
      "trust",
      "smith",
      "stood",
      "thing",
      "truth",
      "smoke",
      "store",
      "think",
      "twice",
      "solid",
      "storm",
      "third",
      "under",
      "solve",
      "story",
      "those",
      "undue",
      "sorry",
      "strip",
      "three",
      "union",
      "sound",
      "stuck",
      "threw",
      "unity",
      "south",
      "study",
      "throw",
      "until",
      "space",
      "stuff",
      "tight",
      "upper",
      "upset",
      "whole",
      "waste",
      "wound",
      "urban",
      "whose",
      "watch",
      "write",
      "usage",
      "woman",
      "water",
      "wrong",
      "usual",
      "train",
      "wheel",
      "wrote",
      "valid",
      "world",
      "where",
      "yield",
      "value",
      "worry",
      "which",
      "young",
      "video",
      "worse",
      "while",
      "youth",
      "virus",
      "worst",
      "white",
      "worth",
      "visit",
      "would",
      "vital",
      "voice",
    ],
    "Hard": [
      "should",
      "states",
      "before",
      "united",
      "people",
      "during",
      "public",
      "number",
      "system",
      "within",
      "school",
      "little",
      "report",
      "county",
      "second",
      "office",
      "action",
      "health",
      "amount",
      "period",
      "having",
      "social",
      "effect",
      "called",
      "person",
      "course",
      "change",
      "family",
      "others",
      "figure",
      "either",
      "though",
      "common",
      "making",
      "result",
      "matter",
      "better",
      "always",
      "rather",
      "policy",
      "become",
      "things",
      "around",
      "income",
      "nature",
      "energy",
      "method",
      "street",
      "center",
      "market",
      "almost",
      "church",
      "rights",
      "member",
      "record",
      "except",
      "single",
      "review",
      "future",
      "higher",
      "itself",
      "reason",
      "enough",
      "months",
      "annual",
      "design",
      "series",
      "ground",
      "father",
      "growth",
      "toward",
      "groups",
      "agency",
      "return",
      "became",
      "direct",
      "letter",
      "source",
      "notice",
      "mother",
      "volume",
      "points",
      "senate",
      "theory",
      "motion",
      "values",
      "twenty",
      "supply",
      "living",
      "answer",
      "manner",
      "normal",
      "charge",
      "really",
      "length",
      "needed",
      "strong",
      "placed",
      "passed",
      "unless",
      "degree",
      "august",
      "proper",
      "issues",
      "taking",
      "credit",
      "across",
      "french",
      "region",
      "recent",
      "claims",
      "entire",
      "extent",
      "appear",
      "safety",
      "weight",
      "bureau",
      "longer",
      "former",
      "modern",
      "looked",
      "nearly",
      "stated",
      "levels",
      "issued",
      "beyond",
      "simple",
      "likely",
      "estate",
      "plants",
      "middle",
      "author",
      "latter",
      "survey",
      "prices",
      "turned",
      "actual",
      "demand",
      "nation",
      "moment",
      "larger",
      "indeed",
      "forces",
      "active",
      "island",
      "behind",
      "seemed",
      "simply",
      "wanted",
      "status",
      "fiscal",
      "effort",
      "german",
      "coming",
      "spring",
      "appeal",
      "object",
      "boston",
      "spirit",
      "factor",
      "follow",
      "regard",
      "giving",
      "budget",
      "sample",
      "summer",
      "access",
      "places",
      "served",
      "caused",
      "formed",
      "courts",
      "cities",
      "impact",
      "master",
      "relief",
      "police",
      "forest",
      "friend",
      "remain",
      "papers",
      "permit",
      "orders",
      "powers",
      "events",
      "showed",
      "obtain",
      "thirty",
      "duties",
      "worked",
      "fourth",
      "easily",
      "square",
      "highly",
      "mental",
      "canada",
      "agreed",
      "raised",
      "valley",
      "useful",
      "merely",
      "branch",
      "inches",
      "choice",
      "output",
      "closed",
      "winter",
      "pounds",
      "create",
      "inside",
      "soviet",
      "trying",
      "myself",
      "assets",
      "animal",
      "fields",
      "reduce",
      "desire",
      "causes",
      "joseph",
      "injury",
      "double",
      "moving",
      "agents",
      "bottom",
      "models",
      "season",
      "editor",
      "speech",
      "leaves",
      "damage",
      "opened",
      "marked",
      "please",
      "failed",
      "memory",
      "excess",
      "avenue",
      "search",
      "saying",
    ]
  };

  late String targetWord;
  List<String> attempts = [];
  int currentAttempt = 0;

  List<List<String>> grid = [];
  List<List<Color>> gridColors = [];

  final TextEditingController _controller = TextEditingController();

  @override
  void initState() {
    super.initState();
    startNewGame();
  }

  void startNewGame() {
    setState(() {
      targetWord = wordLists[widget.mode]![
          Random().nextInt(wordLists[widget.mode]!.length)];
      attempts.clear();
      currentAttempt = 0;

      grid =
          List.generate(6, (_) => List.generate(widget.wordLength, (_) => ''));
      gridColors = List.generate(
          6, (_) => List.generate(widget.wordLength, (_) => Colors.black54));
    });
  }

  void checkWord(String guess) {
    if (guess.length != widget.wordLength) return;
    if (!RegExp(r"^[a-zA-Z]+$").hasMatch(guess)) {
      _showMessage("Invalid input. Use English letters only.");
      return;
    }
    if (attempts.contains(guess)) {
      _showMessage("You already guessed this word!");
      return;
    }

    attempts.add(guess);

    // Step 1: Track letter counts in the target word
    Map<String, int> targetLetterCount = {};
    for (var letter in targetWord.split('')) {
      targetLetterCount[letter] = (targetLetterCount[letter] ?? 0) + 1;
    }

    // Step 2: First pass - Mark correct letters (green)
    List<String> currentRow = List<String>.filled(widget.wordLength, '');
    List<Color> currentColors =
        List<Color>.filled(widget.wordLength, Colors.grey);

    for (int i = 0; i < widget.wordLength; i++) {
      currentRow[i] = guess[i];
      if (guess[i] == targetWord[i]) {
        currentColors[i] = const Color.fromARGB(255, 73, 175, 77);
        targetLetterCount[guess[i]] = targetLetterCount[guess[i]]! - 1;
      }
    }

    // Step 3: Second pass - Mark misplaced letters (yellow)
    for (int i = 0; i < widget.wordLength; i++) {
      if (currentColors[i] == const Color.fromARGB(255, 72, 172, 76)) continue;
      if (targetLetterCount[guess[i]] != null &&
          targetLetterCount[guess[i]]! > 0) {
        currentColors[i] = Colors.amber;
        targetLetterCount[guess[i]] = targetLetterCount[guess[i]]! - 1;
      } else {
        currentColors[i] = Colors.grey;
      }
    }

    // Step 4: Update the grid and attempt counter
    setState(() {
      grid[currentAttempt] = currentRow;
      gridColors[currentAttempt] = currentColors;
      currentAttempt++;
      _controller.clear();

      if (guess == targetWord) {
        _showGameOverDialog(
            "Congratulations! You guessed the word.", Colors.green);
      } else if (currentAttempt >= 6) {
        _showGameOverDialog("Game Over! The word was $targetWord.", Colors.red);
      }
    });
  }

  void _showMessage(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message)),
    );
  }

  void _showGameOverDialog(String message, Color color) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text(
          "Game Over",
          style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
          textAlign: TextAlign.center,
        ),
        content: Text(
          message,
          style: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: color,
          ),
          textAlign: TextAlign.center,
        ),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.pop(context);
              startNewGame();
            },
            child: const Text("Play Again"),
          )
        ],
      ),
    );
  }

  Widget buildGrid() {
    return Column(
      children: List.generate(6, (rowIndex) {
        return Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: List.generate(widget.wordLength, (colIndex) {
            return Container(
              margin: const EdgeInsets.all(4),
              width: 50,
              height: 50,
              alignment: Alignment.center,
              decoration: BoxDecoration(
                color: gridColors[rowIndex][colIndex],
                border: Border.all(color: Colors.white, width: 1.5),
              ),
              child: Text(
                grid[rowIndex][colIndex].toUpperCase(),
                style: const TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                    color: Colors.white),
              ),
            );
          }),
        );
      }),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Word Guess - ${widget.mode} Mode")),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          const SizedBox(height: 20),
          buildGrid(),
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: TextField(
              controller: _controller,
              maxLength: widget.wordLength,
              textAlign: TextAlign.center,
              style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                hintText: "Enter your guess",
              ),
            ),
          ),
          ElevatedButton(
            onPressed: () {
              checkWord(_controller.text.toLowerCase());
            },
            child: const Text("Submit"),
          ),
        ],
      ),
    );
  }
}
